### ISSUE TITLE
Getting exception from plugin when starting homebridge server.

### ISSUE THREAD

**Issue by hanahwill** [bwp91/homebridge-platform-wemo#205]
**What issue do you have? Please be as thorough and explicit as possible.**
I am getting the following exception when I restart the Homebridge server after installing the wemo plugin (from the logs):

[10/17/2020, 16:45:30] Homebridge is running on port 51864.
[10/17/2020, 16:45:31] [Belkin WeMo] Online: 01 Living Room Lamp [6038E0E8AFF8]
[10/17/2020, 16:45:32] [Belkin WeMo] Online: Den [24F5A21FFCB2]
[10/17/2020, 16:45:32] [Belkin WeMo] Online: 02 Living Room Lamp [302303F04FC2]
[10/17/2020, 16:45:33] TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:159:42
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:165:23
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.emit (events.js:314:20)
    at SAXParser.onerror (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:123:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at error (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:369:19)
    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:164:12)
    at module.exports.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:123:5)
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:304:18)
[10/17/2020, 16:45:33] Got SIGTERM, shutting down Homebridge...
[10/17/2020, 16:45:38] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
...

**Details of your setup.**
Do you use Homebridge or HOOBS?

Using Homebridge.

Which version of Homebridge/HOOBS do you have?

version 1.1.6

Which version of this plugin (homebridge-platform-wemo) do you have?

version 1.6.1

**Please paste any relevant logs below.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi @hanahwill 
Please try updating to v1.6.2. This should at least stop the everlasting restart of Homebridge and in the logs should provide some insight into why this was happening in the first place.

**Comment by hanahwill** [comment]
Installed v1.6.2 and restarted Homebridge. Here is the log now:

[10/18/2020, 08:07:36] Homebridge is running on port 51864.
[10/18/2020, 08:07:37] [Belkin WeMo] Online: Den [24F5A21FFCB2]
[10/18/2020, 08:07:37] [Belkin WeMo] Online: 01 Living Room Lamp [6038E0E8AFF8]
[10/18/2020, 08:07:38] [Belkin WeMo] Online: 02 Living Room Lamp [302303F04FC2]
[10/18/2020, 08:07:38] [Belkin WeMo] client.getEndDevices error - Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 0
    at error (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:369:19)
    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:164:12)
    at module.exports.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:123:5)
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:314:20)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)

**Comment by bwp91** [comment]
Seems like a problem with one of the dependencies of this plugin.
Could I message you directly on the [Homebridge Discord](https://discord.gg/7X36mdw)?
Thanks

**Comment by bwp91** [comment]
Hi @hanahwill I've just released an update to this plugin, do you still getting the above error on the new version?

**Comment by hanahwill** [comment]
I installed the latest version - 2.0.0. Getting this in the logs now:

[10/26/2020, 12:10:22] [Belkin WeMo] An error occured loading a device - Error: HTTP 400: <html><body><h1>400 Bad Request</h1></body></html>
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/lib/wemo-client.js:68:12)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10/26/2020, 12:10:22] [Belkin WeMo] An error occured getEndDevices() - Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: 0
    at error (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:369:19)
    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/lib/wemo-client.js:163:12)
    at module.exports.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/lib/wemo-client.js:122:5)
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:314:20)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13).

I am going to switch to a different hub vendor. Belkin seems to have discontinued their Wemo Link and their support is pretty bad.

**Comment by bwp91** [comment]
> I am going to switch to a different hub vendor. Belkin seems to have discontinued their Wemo Link and their support is pretty bad.

Other people have their links working well with this plugin (and this version). Would be nice to get this sorted for you. Is your link on the latest firmware? Also, which devices do you have linked to it?
