### ISSUE TITLE
Plugin crashes homebridge process with a UUID TypeError

### ISSUE THREAD

**Issue by HammerAce42** [bwp91/homebridge-platform-wemo#238]
### What issue do you have? Please be as thorough and explicit as possible.

Plugin crashes homebridge process with a UUID TypeError. This caused my homebridge setup to become unusable, until I moved Wemo to a child bridge using the Homebridge beta release. This issue has survived  a plugin disable, and plugin install/uninstall, and manual clearing of Wemo accessories from the cache.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge Docker

* Which version of Homebridge/HOOBS do you have?

Homebridge v1.3.0-beta.57
Also reproduces with latest stable version of Homebridge v1.2.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

raspberrypi
Node.js v14.15.5
NPM v6.14.11

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

Unsure when it started but reproduces with:

2.12.1-2 beta
2.12.0
2.11.0
2.10.0

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Unsure which device specifically is causing the issue, but devices in my home:

Wemo Insight (x3)
Wemo Mini Plug (x2)
Wemo Wifi Switch (1st gen) (x4)

### Please paste any relevant logs below.

```
[2/15/2021, 12:32:55 PM] [Wemo] Restarting Process...
Initializing HAP-NodeJS v0.9.0-beta.127...
[2/15/2021, 12:32:57 PM] [Wemo] Launched external bridge with PID 9272
[2/15/2021, 12:32:57 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2/15/2021, 12:32:57 PM] [Wemo] Loaded homebridge-platform-wemo v2.12.0 successfully
[2/15/2021, 12:32:57 PM] Loaded 0 cached accessories from cachedAccessories.0ED91EF61ACA.
Preparing Advertiser for 'Wemo 80DA' using bonjour-hap backend!
[2/15/2021, 12:32:58 PM] [Wemo] [v2.12.0] initialised. Setting up device discovery.
[2/15/2021, 12:32:58 PM] [Wemo] Listener server port [45505].
[2/15/2021, 12:32:58 PM] [Wemo] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
Starting to advertise 'Wemo 80DA' using bonjour-hap backend!
[2/15/2021, 12:32:58 PM] Homebridge v1.3.0-beta.57 (Wemo) is running on port 50608.
[2/15/2021, 12:32:58 PM] [Wemo] [N Bathroom Exhaust] has been added to Homebridge.
[2/15/2021, 12:32:58 PM] [Wemo] [N Bathroom Exhaust] initial subscription for service [urn:Belkin:service:basicevent:1].
[2/15/2021, 12:32:58 PM] [Wemo] [N Bathroom Exhaust] initialised with s/n [redacted] and mac address [redacted]
[2/15/2021, 12:32:59 PM] [Wemo] [Humidifier] has been added to Homebridge.
[2/15/2021, 12:32:59 PM] [Wemo] [Humidifier] could not be initialised as Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined at Outlet.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:333:15).
[2/15/2021, 12:32:59 PM] [Wemo] [uuid:Lightswitch-1_0-221417K1301204] incoming notification:
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>0</BinaryState>
</e:property>
</e:propertyset>


[2/15/2021, 12:32:59 PM] [Wemo] [N Bathroom Exhaust] received update [binaryState: 0].
[2/15/2021, 12:32:59 PM] [Wemo] [Chair] has been added to Homebridge.
[2/15/2021, 12:32:59 PM] [Wemo] [Chair] could not be initialised as Cannot add a Characteristic with the same UUID as another Characteristic in this Service: undefined at Outlet.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:333:15).
[2/15/2021, 12:33:00 PM] [Wemo] [Toilet Exhaust] has been added to Homebridge.
[2/15/2021, 12:33:00 PM] [Wemo] [Toilet Exhaust] initial subscription for service [urn:Belkin:service:basicevent:1].
[2/15/2021, 12:33:00 PM] [Wemo] [Toilet Exhaust] initialised with s/n [redacted] and mac address [redacted]
TypeError: uuid was not a valid UUID or short form UUID
    at Object.toShortForm (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:96:29)
    at eveCurrentConsumption.Characteristic.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:13)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:639:82
    at Array.map (<anonymous>)
    at Outlet.Service.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:639:45)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1070:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1070:31)
    at Bridge.Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1077:36)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1284:29)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[2/15/2021, 12:33:00 PM] [Wemo] Child bridge process ended
[2/15/2021, 12:33:00 PM] [Wemo] Process Ended. Code: 1, Signal: null
[2/15/2021, 12:33:07 PM] [Wemo] Restarting Process...
Initializing HAP-NodeJS v0.9.0-beta.127...
[2/15/2021, 12:33:09 PM] [Wemo] Launched external bridge with PID 9291
[2/15/2021, 12:33:09 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2/15/2021, 12:33:09 PM] [Wemo] Loaded homebridge-platform-wemo v2.12.0 successfully
[2/15/2021, 12:33:09 PM] Loaded 4 cached accessories from cachedAccessories.0ED91EF61ACA.
(node:9291) UnhandledPromiseRejectionWarning: TypeError: uuid was not a valid UUID or short form UUID
    at Object.toShortForm (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:96:29)
    at Characteristic.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:13)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:639:82
    at Array.map (<anonymous>)
    at Outlet.Service.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:639:45)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1070:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1070:31)
    at Bridge.Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1077:36)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1183:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bwp91** [comment]
Hi,
Thanks for reporting this. Which wemo device types are 'Chair' and 'Humidifier'?

**Comment by HammerAce42** [comment]
Both of those are Wemo Insight switches.

Another puzzling observation I wanted to include - the UUID type error appears even when the config file includes a disable: true flag for this plugin.

**Comment by bwp91** [comment]
Could we message on my discord?
https://discord.gg/cMGhNtZ3tW

**Comment by HammerAce42** [comment]
The beta release fixed the issue. Thanks so much for the rapid fix!
